### ISSUE TITLE
666.66 > 6.66

### ISSUE THREAD

**Issue by mcoyle1960** [Wasted-Audio/wstd-manglr#2]
Hi! I love your work, but... not that much. :)
When buying the plugin yesterday, I was somehow charged $666.66 instead of $6.66.
Sorry, but I'm pursuing a  refund of $660.00. 

Sorry again,
Michael

<edit: removed your email address for privacy reasons>

**Comment by dromer** [comment]
Hey @mcoyle1960 I actually noticed that and tried contacting you about it. There was a different email address that had an invalid domain so the email bounced.

I believe the entire transaction has been reverted as I no longer see you in the list. Hope you get the refund soon (from paypal or itch?).

The itch.io number inputs are not always intuitive, so maybe you pressed `6` too many times.

**Comment by dromer** [comment]
@mcoyle1960 did this work out on your end?
(just want to make sure)

**Comment by mcoyle1960** [comment]
Yes. They refunded immediately. Thank you for the followup.  Enjoy a pint on me. :)

**Comment by dromer** [comment]
Thank you so much!
